"""Generate the client side copies of the specification.

The spec modules in this folder are the single source for the role and
permission matrix, the data model, the table design and the lifecycles. Python
code on AWS imports them directly, so nothing is generated for the backend or
the infrastructure. The browser and the mobile client cannot import Python, so
they get generated copies and never a hand written second version.

    python spec/generate.py           write the generated files
    python spec/generate.py --check   fail when a generated file is stale

Outputs:
    web/src/generated/permissions.ts
    web/src/generated/lifecycle.ts
    web/src/generated/entities.ts
    web/src/generated/keys.ts
"""

from __future__ import annotations

import pathlib
import sys

from atria_spec import keys as KEYS_SPEC
from atria_spec import lifecycle as LC
from atria_spec import model as MODEL_SPEC
from atria_spec import roles as RL

ROOT = pathlib.Path(__file__).resolve().parent.parent
BANNER = (
    "// Generated by spec/generate.py from the Atria Rev B specification.\n"
    "// Do not edit. Change the Python spec and run `python spec/generate.py`.\n"
)

TS_TYPES = {
    "string": "string",
    "int": "number",
    "number": "number",
    "decimal": "number",
    "bool": "boolean",
    "list": "string[]",
    "json": "Record<string, unknown>",
    "date": "string",  # ISO 8601 date, yyyy-mm-dd
    "datetime": "string",  # ISO 8601 instant
    "time": "string",  # local time, HH:mm
    "enum": "string",
    "encrypted": "string",
}


def quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def ts_identifier(name: str) -> str:
    parts = [p for p in name.replace("-", "_").split("_") if p]
    return "".join(p.capitalize() for p in parts)


def enum_members(note: str) -> list[str] | None:
    """Pull an inline enum list out of an attribute note, when it is one."""
    head = note.split(".")[0].strip()
    if "," not in head:
        return None
    members = [m.strip() for m in head.split(",")]
    if all(m and m.replace("_", "").isalnum() and m.upper() == m for m in members):
        return members
    return None


# ------------------------------------------------------------------ permissions
def permissions_ts() -> str:
    out = [BANNER, "", "export const ROLES = ["]
    out += [f"  {quote(r)}," for r in RL.ROLES]
    out += ["] as const;", "", "export type Role = (typeof ROLES)[number];", ""]
    out += [
        'export const SCOPES = ["own", "clinic", "tenant", "none"] as const;',
        "",
        "export type Scope = (typeof SCOPES)[number];",
        "",
    ]
    out += ["export const PERMISSIONS = ["]
    out += [f"  {quote(p)}," for p in RL.MATRIX]
    out += ["] as const;", "", "export type Permission = (typeof PERMISSIONS)[number];", ""]
    out += [
        "/** permission to role to scope. A permission not listed here does not exist. */",
        "export const MATRIX: Record<Permission, Record<Role, Scope>> = {",
    ]
    for permission, scopes in RL.MATRIX.items():
        pairs = ", ".join(f"{role}: {quote(scopes[role])}" for role in RL.ROLES)
        out.append(f"  {quote(permission)}: {{ {pairs} }},")
    out += ["};", ""]
    out += ["export const LANDING: Record<Role, string> = {"]
    for role in RL.ROLES:
        out.append(f"  {role}: {quote(RL.LANDING[role])},")
    out += ["};", ""]
    out += [
        "/** Fields the create flow requires, by role. Enforced in the service, not only the form. */",
        "export const REQUIRED_ON_CREATE: Partial<Record<Role, readonly string[]>> = {",
    ]
    for role, fields in RL.REQUIRED_ON_CREATE.items():
        out.append(f"  {role}: [{', '.join(quote(f) for f in fields)}],")
    out += ["};", ""]
    out += [
        "export interface GuardRule {",
        "  readonly id: string;",
        "  readonly rule: string;",
        "}",
        "",
        "/** Rules the authoriser applies on top of the matrix. */",
        "export const GUARD_RULES: readonly GuardRule[] = [",
    ]
    for rid, text in RL.GUARD_RULES:
        out.append(f"  {{ id: {quote(rid)}, rule: {quote(text)} }},")
    out += [
        "];",
        "",
        "export function scopeFor(role: Role, permission: Permission): Scope {",
        '  return MATRIX[permission]?.[role] ?? "none";',
        "}",
        "",
        "export function permissionsFor(role: Role): Partial<Record<Permission, Scope>> {",
        "  const granted: Partial<Record<Permission, Scope>> = {};",
        "  for (const permission of PERMISSIONS) {",
        "    const scope = scopeFor(role, permission);",
        '    if (scope !== "none") granted[permission] = scope;',
        "  }",
        "  return granted;",
        "}",
        "",
    ]
    return "\n".join(out)


# -------------------------------------------------------------------- lifecycle
def lifecycle_ts() -> str:
    out = [
        BANNER,
        "",
        "export interface Transition<S extends string> {",
        "  readonly from: S | null;",
        "  readonly to: S | null;",
        "  readonly trigger: string;",
        "  readonly note: string;",
        "}",
        "",
    ]
    blocks = [
        ("Appointment", "APPOINTMENT", LC.APPOINTMENT_STATES, LC.APPOINTMENT_TRANSITIONS),
        ("Session", "SESSION", LC.SESSION_STATES, LC.SESSION_TRANSITIONS),
        ("Ticket", "TICKET", LC.TICKET_STATES, LC.TICKET_TRANSITIONS),
    ]
    for label, prefix, states, transitions in blocks:
        out.append(f"export const {prefix}_STATES = [")
        out += [f"  {quote(s)}," for s in states]
        out += ["] as const;", "", f"export type {label}State = (typeof {prefix}_STATES)[number];", ""]
        out.append(f"export const {prefix}_TRANSITIONS: readonly Transition<{label}State>[] = [")
        for frm, to, trigger, note in transitions:
            f_ts = quote(frm) if frm else "null"
            t_ts = quote(to) if to else "null"
            out.append(f"  {{ from: {f_ts}, to: {t_ts}, trigger: {quote(trigger)}, note: {quote(note)} }},")
        out += ["];", ""]

    out += [
        "/** States inside the Scheduled composite state: the record holds grid units. */",
        "export const SCHEDULED_STATES = [",
    ]
    out += [f"  {quote(s)}," for s in LC.SCHEDULED_STATES]
    out += ["] as const satisfies readonly AppointmentState[];", "", "export const TERMINAL_APPOINTMENT_STATES = ["]
    out += [f"  {quote(s)}," for s in LC.TERMINAL_APPOINTMENT_STATES]
    out += [
        "] as const satisfies readonly AppointmentState[];",
        "",
        "export const LIFECYCLES = {",
        "  appointment: { states: APPOINTMENT_STATES, transitions: APPOINTMENT_TRANSITIONS },",
        "  session: { states: SESSION_STATES, transitions: SESSION_TRANSITIONS },",
        "  ticket: { states: TICKET_STATES, transitions: TICKET_TRANSITIONS },",
        "} as const;",
        "",
        "export type Lifecycle = keyof typeof LIFECYCLES;",
        "",
        "/** True when the lifecycle allows the move. Anything else is refused, not ignored. */",
        "export function can(lifecycle: Lifecycle, from: string | null, to: string | null): boolean {",
        "  return LIFECYCLES[lifecycle].transitions.some(",
        "    (t) => t.from === from && t.to === to,",
        "  );",
        "}",
        "",
        "export function nextStates(lifecycle: Lifecycle, from: string | null): string[] {",
        "  const states = LIFECYCLES[lifecycle].transitions",
        "    .filter((t) => t.from === from && t.to !== null)",
        "    .map((t) => t.to as string);",
        "  return [...new Set(states)].sort();",
        "}",
        "",
    ]
    return "\n".join(out)


# --------------------------------------------------------------------- entities
def entities_ts() -> str:
    out = [BANNER, ""]
    enums: list[str] = []
    interfaces: list[str] = []
    meta: list[str] = [
        "/** Attribute metadata, for the data dictionary and runtime validation. */",
        "export const ENTITY_ATTRIBUTES: Record<string, readonly EntityAttribute[]> = {",
    ]

    for group, entities in MODEL_SPEC.MODEL.items():
        interfaces += [f"// {group}"]
        for entity, (description, attributes) in entities.items():
            name = ts_identifier(entity)
            interfaces += [f"/** {description} */", f"export interface {name} {{"]
            meta.append(f"  {quote(entity)}: [")
            for attr, kind, key, note in attributes:
                ts_type = TS_TYPES[kind]
                if kind == "enum":
                    members = enum_members(note)
                    if members:
                        enum_name = f"{name}{ts_identifier(attr)}"
                        listed = ", ".join(quote(m) for m in members)
                        enums += [
                            f"export const {enum_name.upper()} = [{listed}] as const;",
                            f"export type {enum_name} = (typeof {enum_name.upper()})[number];",
                            "",
                        ]
                        ts_type = enum_name
                comment = f"  /** {note} */" if note else ""
                if comment:
                    interfaces.append(comment)
                optional = "" if key in ("PK", "SK") else "?"
                interfaces.append(f"  {attr}{optional}: {ts_type};")
                meta.append(
                    f"    {{ name: {quote(attr)}, kind: {quote(kind)}, key: {quote(key)}, note: {quote(note)} }},"
                )
            interfaces += ["}", ""]
            meta.append("  ],")
    meta += ["};", ""]

    out += [
        "export interface EntityAttribute {",
        "  readonly name: string;",
        "  readonly kind: string;",
        "  readonly key: string;",
        "  readonly note: string;",
        "}",
        "",
    ]
    out += enums
    out += interfaces
    out += meta
    out += ["export const RELATIONSHIPS: readonly (readonly [string, string, string, string])[] = ["]
    for row in MODEL_SPEC.RELATIONSHIPS:
        out.append("  [" + ", ".join(quote(str(cell)) for cell in row) + "],")
    out += ["];", ""]
    return "\n".join(out)


# ------------------------------------------------------------------------- keys
def keys_ts() -> str:
    out = [
        BANNER,
        "",
        "export interface KeyPattern {",
        "  readonly entity: string;",
        "  readonly pk: string;",
        "  readonly sk: string;",
        "  readonly table: string;",
        "}",
        "",
        "export interface IndexDefinition {",
        "  readonly name: string;",
        "  readonly pk: string;",
        "  readonly sk: string;",
        "  readonly answers: string;",
        "}",
        "",
        f"export const MAIN_TABLE = {quote(KEYS_SPEC.MAIN_TABLE)};",
        "",
        "/** Key patterns, one row per entity. The pattern text is the shape, not a template string. */",
        "export const KEY_PATTERNS: readonly KeyPattern[] = [",
    ]
    for entity, pk, sk, table in KEYS_SPEC.KEYS:
        out.append(f"  {{ entity: {quote(entity)}, pk: {quote(pk)}, sk: {quote(sk)}, table: {quote(table)} }},")
    out += ["];", "", "export const INDEXES: readonly IndexDefinition[] = ["]
    for name, pk, sk, answers in KEYS_SPEC.INDEXES:
        out.append(f"  {{ name: {quote(name)}, pk: {quote(pk)}, sk: {quote(sk)}, answers: {quote(answers)} }},")
    out += ["];", ""]
    return "\n".join(out)


TARGETS = {
    "web/src/generated/permissions.ts": permissions_ts,
    "web/src/generated/lifecycle.ts": lifecycle_ts,
    "web/src/generated/entities.ts": entities_ts,
    "web/src/generated/keys.ts": keys_ts,
}


def main(argv: list[str]) -> int:
    check = "--check" in argv
    stale: list[str] = []
    for relative, render in TARGETS.items():
        path = ROOT / relative
        content = render()
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            status = "current"
        elif check:
            stale.append(relative)
            status = "STALE"
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            status = "written"
        print(f"{status:>8}  {relative}")
    if stale:
        print("\nGenerated files are out of date. Run `npm run generate` and commit the result.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
